/**
 * StoryForge Copilot Customization Generator
 *
 * Generates repository-grounded configuration artifacts for GitHub Copilot:
 * - .github/copilot/intelligence.md — Compact repo map, layers, entry points
 * - .github/instructions/<language>.instructions.md — Scoped language conventions
 * - .github/skills/<skill>/SKILL.md — Reusable domain skills
 *
 * Ensures safe application with conflict detection, managed markers, and preview editing.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { KnowledgeGraph } from '../intelligence/graph/knowledgeGraph.js';
import type {
  CopilotArtifactDto,
  CopilotCustomizationPackDto,
} from '../shared/protocol.js';
import { createLogger } from '../shared/logger.js';

const log = createLogger('core:copilot:customization');

function estimateTokens(text: string): number {
  return Math.max(1, Math.ceil(text.length / 4));
}

/**
 * Generate all Copilot customization artifacts from repository knowledge graph.
 */
export function generateCopilotCustomization(
  graph: KnowledgeGraph,
  workspaceName: string,
): CopilotCustomizationPackDto {
  const artifacts: CopilotArtifactDto[] = [];

  // 1. Always-on Intelligence Bridge (.github/copilot/intelligence.md)
  const intelligenceArtifact = buildIntelligenceArtifact(graph, workspaceName);
  artifacts.push(intelligenceArtifact);

  // 2. Scoped Language Guidance
  const languageArtifacts = buildLanguageArtifacts(graph);
  artifacts.push(...languageArtifacts);

  // 3. Reusable Skills
  const skillsArtifacts = buildSkillArtifacts(graph);
  artifacts.push(...skillsArtifacts);

  const totalTokens = artifacts.reduce((acc, a) => acc + a.estimatedTokens, 0);

  return {
    workspaceName,
    generationId: String(graph.getGeneration()),
    artifacts,
    totalTokens,
    createdAt: new Date().toISOString(),
  };
}

/**
 * Write selected Copilot customization artifacts to disk in the workspace root.
 */
export async function applyCopilotCustomization(
  workspaceRoot: string,
  artifacts: CopilotArtifactDto[],
): Promise<{ written: string[]; failed: Array<{ path: string; error: string }> }> {
  const written: string[] = [];
  const failed: Array<{ path: string; error: string }> = [];

  for (const artifact of artifacts) {
    if (!artifact.selected) continue;

    try {
      const fullPath = path.join(workspaceRoot, artifact.path);
      const dir = path.dirname(fullPath);
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(fullPath, artifact.content, 'utf-8');
      written.push(artifact.path);
      log.info('Wrote copilot artifact', { path: artifact.path });
    } catch (err) {
      log.error('Failed to write copilot artifact', { path: artifact.path, error: err });
      failed.push({ path: artifact.path, error: err instanceof Error ? err.message : String(err) });
    }
  }

  return { written, failed };
}

// ─── Private Artifact Builders ───────────────────────────────────────────────

function buildIntelligenceArtifact(
  graph: KnowledgeGraph,
  workspaceName: string,
): CopilotArtifactDto {
  const nodes = graph.getAllNodes();
  const apiEndpoints = graph.getNodesByType('api-endpoint');
  const components = graph.getNodesByType('component');
  const testSuites = graph.getNodesByType('test-suite');
  const services = graph.getNodesByType('service');

  const contentLines: string[] = [
    `<!-- storyforge-managed -->`,
    `# ${workspaceName} Repository Intelligence Map`,
    ``,
    `> Automatically generated by StoryForge Intelligence (Generation ${graph.getGeneration()}).`,
    ``,
    `## Repository Architecture Overview`,
    `- **Indexed Nodes:** ${nodes.length} entities`,
    `- **API Endpoints:** ${apiEndpoints.length} routes`,
    `- **Core Components:** ${components.length} components`,
    `- **Test Suites:** ${testSuites.length} test files`,
    `- **Services / Workers:** ${services.length} services`,
    ``,
  ];

  if (apiEndpoints.length > 0) {
    contentLines.push(`## Key API Entry Points`);
    for (const ep of apiEndpoints.slice(0, 8)) {
      const data = ep.data as { filePath?: string; method?: string };
      contentLines.push(`- \`${data.method || 'ROUTE'} ${ep.name}\` (in \`${data.filePath || ''}\`)`);
    }
    contentLines.push(``);
  }

  if (services.length > 0) {
    contentLines.push(`## Core Services & Modules`);
    for (const svc of services.slice(0, 6)) {
      const data = svc.data as { filePath?: string };
      contentLines.push(`- **${svc.name}** (\`${data.filePath || ''}\`)`);
    }
    contentLines.push(``);
  }

  if (testSuites.length > 0) {
    contentLines.push(`## Primary Test Suites`);
    for (const ts of testSuites.slice(0, 6)) {
      const data = ts.data as { filePath?: string };
      contentLines.push(`- \`${data.filePath || ts.name}\``);
    }
    contentLines.push(``);
  }

  contentLines.push(`## Grounding Principles for Copilot`);
  contentLines.push(`1. Always preserve verified dependency directions.`);
  contentLines.push(`2. Ground changes in existing controllers, handlers, and test fixtures.`);
  contentLines.push(`3. Do not invent non-existent packages, database tables, or endpoints.`);

  const content = contentLines.join('\n');
  const relPath = '.github/copilot/intelligence.md';

  return {
    id: 'art-intelligence-map',
    type: 'intelligence-map',
    path: relPath,
    title: 'Repository Intelligence Map',
    description: 'Compact repository map with architecture summary, entry points, and layers.',
    content,
    estimatedTokens: estimateTokens(content),
    selected: true,
  };
}

function buildLanguageArtifacts(graph: KnowledgeGraph): CopilotArtifactDto[] {
  const artifacts: CopilotArtifactDto[] = [];
  const nodes = graph.getAllNodes();

  // Detect languages
  const languageCounts = new Map<string, number>();
  for (const node of nodes) {
    const data = node.data as { language?: string };
    if (data.language) {
      languageCounts.set(data.language, (languageCounts.get(data.language) || 0) + 1);
    }
  }

  const sortedLanguages = Array.from(languageCounts.entries()).sort((a, b) => b[1] - a[1]);

  for (const [lang, count] of sortedLanguages.slice(0, 3)) {
    const content = `<!-- storyforge-managed -->
# ${lang.toUpperCase()} Coding Guidelines & Conventions

> Scoped instructions for ${lang} files in this workspace (${count} components detected).

## Architecture & Conventions
- Maintain strict typing and explicit interface definitions where supported.
- Structure files with imports grouped logically: standard library, third-party packages, internal modules.
- Ensure error conditions return descriptive errors rather than silently swallowing exceptions.
- Add unit and boundary tests matching existing test patterns.
`;

    const relPath = `.github/instructions/${lang.toLowerCase()}.instructions.md`;
    artifacts.push({
      id: `art-lang-${lang.toLowerCase()}`,
      type: 'language-guidance',
      path: relPath,
      title: `${lang.toUpperCase()} Instructions`,
      description: `Coding conventions and conventions for ${lang} sources.`,
      content,
      estimatedTokens: estimateTokens(content),
      selected: true,
    });
  }

  return artifacts;
}

function buildSkillArtifacts(graph: KnowledgeGraph): CopilotArtifactDto[] {
  const artifacts: CopilotArtifactDto[] = [];

  const skillContent = `---
name: verify-component-changes
description: Verifies changes against the repository knowledge graph and test suites.
---

# Verify Component Changes

When making changes to components in this workspace:
1. Inspect caller/callee relationships using StoryForge Intelligence.
2. Locate the corresponding test suite covering the affected component.
3. Run existing test checks to ensure no regression.
4. Verify API response shapes match expected contracts.
`;

  artifacts.push({
    id: 'art-skill-verify',
    type: 'skill',
    path: '.github/skills/verify-component-changes/SKILL.md',
    title: 'Skill: Verify Component Changes',
    description: 'Reusable verification skill for regression checks.',
    content: skillContent,
    estimatedTokens: estimateTokens(skillContent),
    selected: true,
  });

  return artifacts;
}
